SteamDeckHomebrew/decky-loader

README.md
As mentioned in issues, feels like an area that might need other things adding to it as issues are found :)
=> Note it needing touchscreen input

README.md
this is for developers/testers
=> Update readme to show install instructions

.vscode/launch.json, .vscode/tasks.json
Adds configuration files for debugging the plugin loader with vscode.
=> Add vscode debugging

plugin_loader/loader.py, plugin_loader/static/styles.css, plugin_loader/templates/plugin_view.html
Lets the user write
```html
<link rel="stylesheet" href="/static/styles.css">
```
instead of
```html
<link rel="stylesheet" href="/steam_resource/css/2.css">
<link rel="stylesheet" href="/steam_resource/css/39.css">
<link rel="stylesheet" href="/steam_resource/css/library.css">
```
=> Bundle stylesheets

backend/browser.py, frontend/src/components/settings/pages/PluginList.tsx, frontend/src/plugin-loader.tsx
=> Use deckyState in uninstall menu (fixes #98)

backend/browser.py, backend/helpers.py, backend/main.py, dist/install_nightly.sh, dist/install_prerelease.sh, dist/install_release.sh, dist/uninstall.sh
- Uses environment variables instead of hard coding the "deck" user/group. This
adds support for systems other than the steam deck that are using the DeckUI.
=> Use Environment Variables

frontend/src/components/settings/pages/plugin_list/index.tsx
Moves plugin actions into context menu, adds Reload action
=> Add Plugin Reload Button to Settings

backend/updater.py, frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/components/DeckyState.tsx, frontend/src/components/settings/pages/general/BranchSelect.tsx, frontend/src/components/settings/pages/general/Updater.tsx, frontend/src/components/settings/pages/general/index.tsx, frontend/src/plugin-loader.tsx, frontend/src/utils/hooks/useSetting.ts
=> Addition of proper branch slection

README.md
Quick note about how to open the terminal using the pre-installed Konsole app for users that are either new to linux or Steam Deck.
=> Add note about opening terminal to README

frontend/src/components/Toast.tsx, frontend/src/toaster.tsx
This should fix the QAM lagging and Gamescope crashing.
=> Rewrite toaster hook to not re-create the window

backend/injector.py, backend/main.py
Closes #245 when released via pre-release.
=> Fix desktop mode loop

.vscode/tasks.json, backend/helpers.py, backend/injector.py, backend/loader.py, backend/main.py, backend/updater.py, backend/utilities.py, frontend/rollup.config.js, frontend/src/plugin-loader.tsx
* Fixes desktop mode breaking re-injection
* Fixes AioHttp unclosed client session errors
* Fixes injection race conditions
* Unclutters build and runtime logs
Closes #245
=> Refactoring in preparation for WebSockets

backend/browser.py, backend/loader.py, backend/plugin.py, backend/settings.py, backend/updater.py
This PR should hopefully fix the locale issues discussed in #206
=> Potentially fix locale issues

backend/injector.py
=> maybe working fix for jan 05 beta

README.md
a couple people have had this issue now (both in the discord and out), and it's not really fixable afaik so this seems like the best solution.
=> [readme] add installer issue to common issues

frontend/src/toaster.tsx
Fix for missing notifications on the latest stable branch of the Steam Client.
=> Fix class name shenanigans for toast notification

README.md
=> Minor README fix for build instructions.

backend/browser.py
haven't tested on the actual main branch, but it doesn't break everything on mine.
=> Fix browser.py 

frontend/package.json, frontend/pnpm-lock.yaml, frontend/rollup.config.js, frontend/src/index.tsx
This fixes the localStorage issues with the plugins.
=> Hotfix for i18n where the detector was overriding localStorage

frontend/rollup.config.js, frontend/src/developer.tsx, frontend/src/index.ts, frontend/src/start.tsx
Also removes Navigation shims since they aren't needed anymore as those older versions of DFL that need them don't work.
=> Initial implementation of global DFL instance

backend/browser.py, backend/locales/en-US.json, backend/utilities.py, frontend/src/components/modals/MultiplePluginsInstallModal.tsx, frontend/src/components/settings/pages/plugin_list/index.tsx, frontend/src/plugin-loader.tsx, frontend/src/store.tsx
Also:
* Streamline styling for the plugin list buttons
This fixes issue: #461 
We might need to pull the translations into weblate first? IDK how it is setup @RodoMa92
=> Add update all button to plugin list

.github/workflows/build.yml
This properly fix sqlite3 bundling issues by specifying to pyinstaller to bundle in the sqlite3 library.
=> Properly fix sqlite issues

frontend/package.json, frontend/pnpm-lock.yaml, frontend/src/plugin-loader.tsx, scripts/deckdebug.sh
This fixes various plugins failing to render on Beta
It also fixes occasionally delayed plugin updates due to slow wifi connection and fixes deckdebug.sh segfaulting chromium (LOL)
=> Fix missing components on Oct 2 2024 Steam Beta

frontend/package.json, frontend/pnpm-lock.yaml
This fixes issue: https://steamcommunity.com/app/1675200/discussions/1/4842023333101256645/
Some getter accesses were causing the component to break
=> Fix broken checkboxes on Beta Steam client

frontend/.prettierrc.js, frontend/src/components/DeckyErrorBoundary.tsx
=> Add Decky branch switcher and updater to error boundary

frontend/package.json, frontend/pnpm-lock.yaml
Bump dfl
This fixes issue: Broken ConfirmModal react invariant
=> bump @decky/ui to fix ConfirmModal component

frontend/package.json, frontend/pnpm-lock.yaml
Fixes invariant with ModalRoot component by updating the filter as valve removed the mobx wrapper from the component
=> Fix ModalRoot component on beta

frontend/package.json, frontend/pnpm-lock.yaml
This fixes issue: DialogHeader undefined on beta
=> @decky/ui bump to fix DialogHeader component on beta

frontend/src/components/DeckyState.tsx, frontend/src/components/modals/PluginDisablelModal.tsx, frontend/src/components/settings/pages/plugin_list/index.tsx, frontend/src/components/store/PluginCard.tsx, frontend/src/components/store/Store.tsx, frontend/src/plugin-loader.tsx, frontend/src/plugin.ts
=> Feat disable plugins
