- README.md
- dist/uninstall.sh
Added uninstall script based on the answer provided to #46.
> Uninstall script addition

- README.md
There is no password by default, so people need to set one before running that script.
> Update README.md, password is needed

- frontend/src/plugin-loader.tsx
`body` is being added a property  in the `args` object; however, the request method of aiohttp's ClientSession does not have an argument for `body`. I think the intention was that `body` is meant to be assigned to `data` which already is happening.
> remove body property in args

- backend/main.py
- backend/updater.py
- dist/install_prerelease.sh
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/settings/index.tsx
- frontend/src/components/settings/pages/general/Updater.tsx
- frontend/src/components/settings/pages/general/index.tsx
- frontend/src/components/settings/pages/plugin_list/index.tsx
- frontend/src/index.tsx
- frontend/src/updater.ts
- frontend/tsconfig.json
Adds the ability for decky-loader to update itself via an option in settings, also displaying the current and latest availiable pre-release version. Easily updatable in the future to include a branch select.
This also updates all installed NPM packages in frontend, and edits tsconfig to allow React Fragments to work.
> Updater for decky-loader

- dist/install_prerelease.sh
The current https://raw.githubusercontent.com/SteamDeckHomebrew/decky-loader/main/dist/install_prerelease.sh script doesn't work and errors out when trying to execute.
```
(deck@breezydeck ~)$ ./install_prerelease.sh
Installing Steam Deck Plugin Loader pre-release...
./install_prerelease.sh: line 16: [: too many arguments
curl: no URL specified!
curl: try 'curl --help' for more information
```
This is a quick fix to pass in the variables to jq correctly to rectify this issue.
> Fix jq errors in prerelease script

- README.md
Currently, the links for install/uninstall scripts in the readme still refer to the PluginLoader repo, this can cause confusion for some who are trying to install the plugin loader but using the wrong link
> Readme.md references incorrect github repo

- README.md
In my original PR #124, I forgot to also change the uninstall script reference to the new decky-loader one
> Also change the Uninstall script to the new decky-loader repo name

- backend/browser.py
For some reason this broke installation of plugins when another specific
plugin was present (vibrantDeck)
See https://github.com/libvibrant/vibrantDeck/issues/3
> Don't pass unzip job to event loop

- backend/helpers.py
- backend/main.py
- backend/utilities.py
- frontend/src/components/settings/pages/general/RemoteDebugging.tsx
- frontend/src/components/settings/pages/general/index.tsx
Alternative approach to #61 
This disables the `steam-web-debug-portforward.service` unit on startup, while offering a toggle in the UI which enables and starts the service.
I am personally not quite sure if enabling/disabling is the right approach, as that would be persistent, even if decky would be uninstalled. So maybe we can just start/stop it instead? Feel free to leave your thoughts here.
> Add CEF Remote Debugging toggle

- frontend/src/components/store/PluginCard.tsx
Fixed the tags overlapping when they wrap into a second line
Current:
Proposed changes:
Note: I have not been able to get the deck.sh script to work to deploy the modified version on my deck and I've gotten too frustrated with it for now.
> Better wrapping of plugin tags

- backend/plugin.py
Trying to read the contents of a `/proc/{pid}/environ` file fails within decky-loader when the UID is set but the GID is not when dropping permissions. 
I am using the proc filesystem to get the environment variable `MANGOHUD_CONFIGFILE` from the `mangoapp` process as a more reliable way to determine the configuration file location. Getting the contents as root works, but I'd rather not have a plugin run as root if it's not necessary.
``` python
Python 3.10.2 (main, Jan 15 2022, 19:56:27) [GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import os
>>> with open('/proc/62404/environ', 'r') as f:
...   _ = f.read()
... 
>>> os.setuid(1000)
>>> with open('/proc/62404/environ', 'r') as f:
...   _ = f.read()
... 
Traceback (most recent call last): …
```
> set gid along with uid

- backend/plugin.py
This fix should it make possible now to pass an arbitrary amount of data to the backend via plugin calls.
Fixes #158
> Fix LimitOverrunError when a lot of data is passed to the backend (fixes #158)

- backend/browser.py
Grab the plugin path using find_plugin_folder since the plugin name is not the plugin folder name.
> Grab Folder Name instead of .zip name

- README.md
updated installation steps to reflect the required confirmation and system reboot step
> updated installation steps

- README.md
Change the link to https://beta.deckbrew.xyz so the plugins shown actually reflect the available plugins.
Also, people are sometimes confused by the wording, and this should hopefully make it clearer that the website doesn't actually work for downloading plugins.
example of confusion in issue #179
> (readme) Make store link go to beta.deckbrew + Change wording

- README.md
This seems like a reasonable change as it hasn't been called PluginLoader for a while.
Would it have been better to make an issue suggesting the change instead or is this fine?
> Change 'PluginLoader' to 'Decky Loader' in readme

- frontend/src/tabs-hook.ts
The scroll root's path changed in the latest Steam Client beta update. This PR makes so that Decky should be able to find the scroll root using a recursive function that goes down the sibling and child nodes. This fixes issue #197 from what I can tell. Tested personally to work on both the latest Beta update, and the stable update, and works on both.
> Fixed an issue regarding the scroll root path

- frontend/src/components/store/PluginCard.tsx
This PR attempts to add plugin descriptions to the deck-store like those found on the web version.
As a new Steam Deck user, I found it extremely frustrating to have to use another device to see exactly what a plugin did, if the name of the plugin didn't make it's purpose obvious.
_Unfortunately, my current env is completely Windows based so I cannot test this change locally, and setting up an Arch env in WSL2 is proving to be more time consuming than such a simple PR deserves. I would appreciate any assistance in testing this fix visually._
> Add plugin description to Store PluginCard

- README.md
While the video does *show* the password not appearing, he doesn't mention it. This should reduce the occasional user confusion of passwords not appearing.
> README: password typing clarification

- frontend/src/tabs-hook.ts
After diagnosing the issue regarding Decky not loading in select situations but printing the error that states it was unable to find scroll root, it appeared to be caused by the recursive function never hitting 30 levels of depth, thus it never rechecks the tree. This seems to be partially caused by TabsHook loading before the QAM has been initialized in Library Init Stage 2, which occurs randomly on occassion, and seems to be less likely to occur on Steam Decks that don't have the lock screen setup. The proposed fix is a revert of some portion of the code to where a while loop is used after the initial call attempting to get the scroll root instead of just exiting, as well as removing the portion that would continue the recursive function should 30 recursive calls be made. 
On another …
> Use a conditional while loop for when the scroll root is not found.

- backend/main.py
- frontend/src/components/PluginView.tsx
- frontend/src/components/QuickAccessVisibleState.tsx
- frontend/src/plugin-loader.tsx
- frontend/src/tabs-hook.tsx
Also makes plugins not render unless the Quick Access Menu is visible.
> Allow B button to close active plugin and return to menu.

- backend/injector.py
- dist/install_prerelease.sh
- dist/install_release.sh
Tested with the help of @nabel0
Not 100% sure on the `network-online.target`. I think this only works when any network interface is up. With wifi disabled, after a reboot, decky still boots. I seem to have a loopback network interface that goes up pretty quickly, so that may be why. Someone who knows sytemd better than me should chime in on this
> Add timeout to get tabs request, wait for network online target before booting decky

- backend/updater.py
- dist/install_prerelease.sh
- dist/install_release.sh
- dist/plugin_loader-prerelease.service
- dist/plugin_loader-release.service
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/settings/pages/general/BranchSelect.tsx
- frontend/src/store.tsx
- frontend/src/tabs-hook.tsx
- frontend/src/updater.ts
With @suchmememanyskill's recent updates to help with a potential race condition between plugins and loader, users would have to re-install decky to get their systemd services updated but now updates with update the service file as well.
This has been pretty been well tested but review is still requested.
> Systemd service updating

- backend/helpers.py
- backend/settings.py
With this, the files are copied automatically in the settings folder if present in the root directory (I'm scanning for file extension name (json), so if you will think to add json files to the root directory this will need to be changed) and copy them back to the settings folder. Permission issues on the settings folder are automatically fixed, both on creation and even if they are not matching after.
As far as my small tests are gone, it does seems to work perfectly fine now.
Let me know if I need to change anything else.
Marco
> Fix for wrong path for settings json files

- .github/workflows/build.yml
- frontend/src/store.tsx
Currently, custom stores are supported but the main CDN is always used. This prevents independent custom stores from existing.
This adds support for a providing a custom artifact url for every plugin version in the store. When that field is not provided (or null), it falls back to the main store's CDN.
> Add custom CDN support for custom stores

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/toaster.tsx
This PR does two main things:
- Replaced the settingsModule from Toaster with window.settingsStore because:
- window.NotificationStore is already being used
- from personal testing (SteamOS Preview, Decky-Loader Prerelease v2.4.4-pre1), decky-loader currently doesn't respect user-selected settings DisableAllToasts or DisableToastsInGame, and will send a toast when plugin updates are available
- Added properties matching those from SteamOS for `showToast`, `playSound`, `sound`, and `eType` to allow plugin developers the ability to have custom notification settings for their plugin (Toast+Sound, Toast only, Sound only, No notification)
- showToast: boolean, shows a toast, defaults to true
- playSound: boolean, plays sound, defaults to true
- sound: number (0-25), audio sfx played when …
> feat(MoreCustomizableToasts): Allow plugin developers to customize some toast properties

- dist/install_prerelease.sh
- dist/install_release.sh
Adds automatic enabling of cef debugging in the (soon to be old) installers.
Works fine on my deck.
Might be worth adding an `echo "Enabling CEF debugging"` to the file to alert the user, but probably not.
> Add cef debugging to the installer scripts

- .github/ISSUE_TEMPLATE/feature_request.yml
adds feature requests as another issue type. 
(if you don't want to merge this, then `.github/ISSUE_TEMPLATE/config.yml` should probably have `blank_issues_enabled` re-enabled or feature requests will have to fit within the bug request template which is annoying)
----
> Add feature requests as an issue template

- backend/main.py
- frontend/rollup.config.js
- frontend/src/components/modals/filepicker/patches/library.ts
- frontend/src/plugin-loader.tsx
- frontend/src/steamfixes/README.md
- frontend/src/steamfixes/index.ts
- frontend/src/steamfixes/reload.ts
- frontend/src/steamfixes/restart.ts
- frontend/src/tabs-hook.tsx
Switches back to reloading the STeam UI for updates, with a workaround to fix the UI disappearing.
Also fixes "Restart Steam" breaking Decky (as it breaks CEF debugging) by simply replacing its behaivour with shutting down steam, and since Gamescope-session restarts Steam if it exist anyway this results in no noticable change for users.
> Fix reloading UI on updates and restarting Steam

- README.md
Changes the readme's terminal commands to point at decky-installer. The actual installer files should probably remain in /dist for a while though as to not break old tutorials (wait till there's more new ones) and until the emudeck change makes it to release.
> [readme] change terminal commands to point at decky-installer

- frontend/src/plugin-loader.tsx
The http_request method requires the `body` attribute to be named `data`, the method renames the input's body to data to make it work, however it doesn't delete the original body property, so http_request errors out if you attempt to include a body. This just deleted the body property after it's been renamed to data.
Has been built and tested using a function akin to the following, and everything now works.
```
fetchNoCors(`https://example.com`, {
method: "POST",
headers: { "Content-Type": "application/json" },
body: JSON.stringify({ message: "Example Message" }),
})
```
> Fix http_request and fetchNoCors methods erroring when including a body.

- backend/helpers.py
- backend/main.py
- backend/plugin.py
- backend/settings.py
- backend/updater.py
This change aims to suggest recommended settings, runtime data, logs paths to plugins through environment variables in order to propose a common storage guideline for plugins to follow.
In doing so I've cleaned up and hopefully improved the helper functions for the paths a bit. For instance the user is deduced from the path the `PluginLoader` is launched from by matching with the home directory specified in the passwd entry.
The environment variables that are exposed and can be retrieved from a python script with `os.environ["DECKY_HOME"]` or the appropriate functions when using a custom backend binary are as follows:
- `HOME`: the home directory of the effective user running the process
+ e.g.: if `root` was specified in the plugin's flags it will be `/root` otherwise the user whose home …
> Expose useful env vars to plugin processes

- act/run-act.sh
By specifying the `linux/amd64` Docker container architecture, hardware that doesn't use `amd64` (ex. Apple silicon processors) is able to build Decky Loader artifacts using the `act/run-act.sh` script.
Please feel free to test with and without the provided changes and report the changes across different systems.
> Add support for more hardware when building

- frontend/src/router-hook.tsx
The newest beta renamed `GamepadUI.Settings.Root()` to `Settings.Root()` the component which decky attempts to inject into.
This fix searches for `Settings.Root()`, which would be a part of `GamepadUI.Settings.Root()`, meaning that it doesn't break anything for people who haven't updated yet.
> Fix fullscreen route inject issues caused by Feb. 17th beta.

- .github/workflows/build.yml
- backend/helpers.py
- backend/plugin.py
- plugin/decky_plugin.py
- plugin/decky_plugin.pyi
This pull request adds support for exposing a decky python module to help plugins with useful constants and functions.
There's support for a `_migration` to be exposed in the `Plugin` class to move files to the recommended locations.
*Why not just do it in the `_main` ?* Even though right now it's simply executed right before `_main` by having the migrations in a separate method it could give the loader more flexibility in the future to process them all before the plugins themselves or treat their execution differently.
The `plugin/` folder represents the public interface of the loader to be used by the plugins and is to be included as additional data folder in the resulting loader executable. The path to the public interface is injected just before loading the plugin module as well as …
> Expose a 'decky_plugin' module to decky plugins

- backend/updater.py
- frontend/src/tabs-hook.tsx
- frontend/src/toaster.tsx
This also implements @TrainDoctor 's patch for having the newest stable release also show in pre-release channel.
The fix for the QAM injection was simply to up the iteration count from 55 to 65
For the toaster, Valve had renamed it from `toastmanager_ToastPlaceholder` to `gamepadtoasts_GamepadToastPlaceholder`
> Fix QAM And Toaster Injection for Mar 02 Beta

- backend/browser.py
While investigating this bug it quickly became apparent (after adding some debug prints) that key environ vars (such as DECKY_PLUGIN_LOG_DIR) had the wrong values.  This was an indirect result of how those values were built. Example here from LOG_DIR:
environ["DECKY_PLUGIN_LOG_DIR"] = path.join(environ["DECKY_HOME"], "logs", self.plugin_directory)
Note the last parameter to path.join is the self.plugin_directory.  But it is important to notice (though it might have once been a full directory path) all other users of this code are actually passing in just the plugin name for this parameter.  And if we incorrectly pass in a full abs path (such as /home/deck/homebrew/dev/plugins in this case) - any abspath is guaranteed to completely replace all prior arguments to path.join.
Note - this bug …
> fix #390 the plugin_directory argument to import_plugin was incorrect

- backend/plugin.py
- plugin/decky_plugin.py
- plugin/decky_plugin.pyi
A situation came up in [my plugin](https://github.com/jvyden/deck-kdeconnect/blob/main/main.py#L7-L22) where I needed to get the user's id, and saw no variable in `decky_plugin` for it, so I added it using existing APIs.
Normally this should be `1000` but it can technically be different, so here we are.
*P.S.: This is unfortunately untested due to complications regarding getting Decky running locally, so it would be appreciated if someone could give this a proper test :pray:*
> Expose USER_ID and DECKY_USER_ID to plugins

- backend/injector.py
Latest beta update seems to have renamed the shared steam context tab to 'SharedJSContext'. Injecting current frontend code into that tab seems to be working fine
> Shared Ctx tab rename to SharedJSContext

- backend/updater.py
- frontend/src/components/settings/pages/general/Updater.tsx
Spent *way* too long on this, but hey its done and i can finally move onto other things.
Currently, this achieves this by filtering the `remoteVersions` list in python, however it could eventually be refactored to only filter what is returned to the frontend, that way the backend always has the full dataset
> Make patch notes modal only show current branch

- backend/localplatform.py
- backend/updater.py
This adds an environment variable that stops decky from updating it's systemd unit/config, so any configuration in it will not be lost. Default behaviour stays the same: the systemd unit/config gets updated every time decky updates
Tl;dr: Simply add `Environment=KEEP_SYSTEMD_SERVICE=1` to decky's systemd unit/config to stop it from being overwritten
PS: This also fixes a bug where the LIVE_RELOAD environment variable was ineffective
> Add env var to not replace systemd service file

- frontend/src/components/store/PluginCard.tsx
This just adapts the store styling to:
* Not center the text
* Pull the root warning to bottom
* make buttons full width and minwidth for version select
> adjust some small store stylings

- backend/loader.py
- frontend/src/components/settings/pages/plugin_list/index.tsx
When finished, when in the frontend a plugin is requested to be reloaded, the backend will now also reload
> Plugin backend reload

- backend/browser.py
- backend/locales/en-US.json
- backend/settings.py
- frontend/.gitignore
- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/rollup.config.js
- frontend/src/components/DeckyState.tsx
- frontend/src/components/PluginView.tsx
- frontend/src/components/modals/PluginUninstallModal.tsx
- frontend/src/components/settings/pages/plugin_list/PluginListLabel.tsx
- frontend/src/components/settings/pages/plugin_list/index.tsx
- frontend/src/hidden-plugins-service.tsx
- frontend/src/plugin-loader.tsx
> Add functionality to hide plugins from quick access menu

- backend/updater.py
- frontend/src/components/settings/pages/general/BranchSelect.tsx
This fixes issue: #472
This issue should only happen on new installs where the branch isn't set in settings, but might fix other situations too.
> When decky is uncertain of branch, set the setting to match the guess

- backend/browser.py
This fixes issue: When uninstalling a plugin on latest release, it fails as it's trying to remove an element from a list that may not exist in said list (specifically, the list that tracks hidden plugins). This pull request fixes that.
> Fix uninstalling plugins

- backend/plugin.py
This fixes the imfamous 'emudeck' plugin loading issue (which turns out, is not caused by emudeck). When installing a root plugin as the first plugin, any non-root plugins installed after will fail to load. This PR fixes that
> Make sure settings/data/logs gets created as user

- backend/locales/en-US.json
- frontend/src/components/TitleView.tsx
This simple PR is in preparation for custom titleviews. Since plugins may reuse the same icons or use ones that aren't universally recognized, it will be a good practice to disambiguate Decky's buttons with labels. This also has precedence in the Steam UI, where any icon-only button has a matching description.
> Add descriptions to Decky titleview DialogButtons

- backend/locales/en-US.json
- frontend/src/components/store/Store.tsx
- frontend/src/store.tsx
_I added two new strings to the English JSON, let me know if I need to do anything else._
This adds a new warning to the testing store stating that plugins are bleeding-edge and to leave feedback on GitHub.
_Hyperlink looks weird due to a low quality screenshot, looks better on Deck._
> Add testing store info to browse tab

- backend/localplatformlinux.py
- backend/main.py
This fixes the issue issue mentioned here https://github.com/Jovian-Experiments/Jovian-NixOS/pull/111 and here https://github.com/SteamDeckHomebrew/decky-loader/issues/446#issuecomment-1637177041
While decky doesn't really support running as the user, as it breaks some of its features, we might as well make it functional where possible. This *has not been tested*, i'll test it in a moment and then merge it myself, so I don't really know who I'm writing this for or why I'm making it a PR instead of just commiting to main...
> Ignore chmod if decky is not run as root

- .github/workflows/build.yml
- requirements.txt
While using Decky on main OS, I discovered that SDH-PlayTime was failing to load throwing an sqlite import error. After updating Python to the latest stable, AIOHttp to the latest to allow to compile it correctly and PyInstaller in order to make it actually produce a runnable binary version, SDH-PlayTime started to work again fine.
This need to be tested on other OS version and with different plugin, but for my initial testing it seems to work perfectly fine.
> Bugfix: Unable to load _sqlite3 on main SteamOS

- frontend/src/components/TitleView.tsx
- frontend/src/plugin.ts
This is an addition that allows plugin developers to change the titleView of their plugin. Currently, it is just a `<div style={{ flex: 0.9 }}>{activePlugin.name}</div>`. If a plugin has the `titleView` prop in their definePlugin return value, it will now display that instead of the boilerplate name.
This does not allow for removal of the back button, as that is crucial to ensuring people can exit out of plugins, the custom titleView slots in to the right of the back button.
> Add Custom `TitleView`

- backend/localplatform.py
- backend/updater.py
This fixes the issue for SELinux users where the loader would not make itself executable.
If a user sets the env var `DECKY_SELINUX` = `1` it will make decky run `chcon` on the new executable file, allowing it to work (on selinux). I'll merge this once it's been tested by someone who uses selinux.
> Make the updater work properly on SELinux

- .github/workflows/build-win.yml
- .github/workflows/build.yml
- CI Change, not relevant
This fixes that a lot of time is spent waiting on windows CI builds, as it's now split into a seperate file/actions run. Also, this adds a console-less windows version of the pluginloader binary.
> Split windows workflow

- plugin/decky_plugin.py
Currently, decky plugins utilising decky_plugin.py endlessly write logs to the same file, eventually leading to gigantic log files. This fixes that by naming the log file after the current time. Effectively, every time a plugin is ran a new log file is created. This PR also deletes any .log file older than the 5 newest files. Example new log name: `2023-08-11 14.50.16.log`
> Only keep up to 5 recent logs of runs of plugins

- backend/src/browser.py
This will currently only work with the testing store, as the changes are not yet on the main store.
Whenever a plugin is installed the loader will send a request to an /increment endpoint on the plugin server so it can increment the number of downloads/updates by one. This will be used for sorting by popularity at some point in the future, once there's enough downloads recorded to make the sort meaningful.
> Count the number of installs for each plugin

- backend/src/localplatformlinux.py
this prevents needless prompts opening up
Verifies a service is active before trying to start or stop it.
> Check if Linux service is running before trying to start or stop it

- backend/src/localplatformlinux.py
Replaces platform specific chmod implementation with os.chmod
os.chmod is already compatible with Linux and Windows and is better at achieving the intended behavior on Windows than a noop.
Also gets rid of potential complicates with unique chmod implementations
> replace platform chmod with os.chmod

- backend/src/plugin.py
This can prevent race conditions where unload is clearing data but main is still working with it
During the unload long-running code is still active causing possible race conditions when unloads cleans up data which main was referencing.
```py
class Plugin:
data = []
async def _main(self):
while True:
self.data.append(len(self.data))
decky_plugin.logger.info(self.data)
await asyncio.sleep(0.1)
async def _unload(self):
self.data = None
```
> Call plugin unload function after stopping event loop

- backend/src/injector.py
- frontend/package.json
- frontend/pnpm-lock.yaml
On January 18th, a new steam client beta was released bumping CEF to chromium 109, this also changed some tab names, as well as breaking the Navigation object on Decky Frontend Lib.
This PR fixes the tab names (courtesy of @suchmememanyskill), as well as bumping DFL to the new fixed verison.
I have tested both commits on both an LCD Deck running SteamOS Stable and an OLED Deck running SteamOS beta, everything works again. Plugins using global DFL shouldn't have to update anything.
> fix: Fix on Chromium 109 beta

- backend/src/plugin.py
Functions don't appear to run after the event loop closes, so the unload function is never actually run.
> Revert "Call plugin unload function after stopping event loop"

- backend/src/utilities.py
Adds case insensitive matching to fix files not showing when using `validFileExtensions` in `openFilePickerV2()` .
Example:
```tsx
<FilePicker
validFileExtensions={['.png']} // this would match ".png" but not ".PNG"
/>
```
> fix(filepicker_ls): use case insensitive matching for file exts

- backend/src/browser.py
- frontend/src/toaster.tsx
Currently the development plugin installation from ZIP / URL is broken partially, due to relying on ZIP name as the plugin name. This commit fixes the issue, by parsing the plugin name from the folder containing `plugin.json` from the ZIP. I tested this on my Steam Deck OLED and can confirm it to fix the issue. I installed a ZIP which previously failed installation and it now works without issue with this commit.
https://github.com/SteamDeckHomebrew/decky-loader/issues/527#issuecomment-1908169324
https://github.com/SteamDeckHomebrew/decky-loader/issues/527#issuecomment-1908947062
This fixes issue: #527
> Get plugin name for development ZIP during installation

- backend/locales/en-US.json
- backend/src/browser.py
- frontend/src/components/DeckyState.tsx
- frontend/src/components/modals/PluginUninstallModal.tsx
- frontend/src/components/settings/index.tsx
- frontend/src/components/settings/pages/plugin_list/PluginListLabel.tsx
- frontend/src/components/settings/pages/plugin_list/index.tsx
- frontend/src/frozen-plugins-service.tsx
- frontend/src/plugin-loader.tsx
Allows Developers (when Developer mode is available) to freeze updates for a specific plugin. When frozen, updates will no longer be checked for that plugin. See https://discord.com/channels/960281551428522045/960284311444131840/1201162635224301680 for suggestion.
> [Feature] Freeze updates for devs

- backend/src/browser.py
- backend/src/plugin.py
https://github.com/SteamDeckHomebrew/decky-loader/issues/536
This fixes issue: #536
> Add Plugin.uninstall callback support

- .envrc
- .gitignore
- flake.lock
- flake.nix
Adds a flake.nix file so developers can get all relevant dependencies by just typing `nix develop`. 
Uses poetry2nix so all python deps will get installed at the correct versions without needing to update the flake. 
It's currently set up to build each python library from source instead of using the wheel but this can be changed if preferable.
Possibly an issue is that the env is not automatically updated when new deps are added, it must be restarted.
Also the way pyright is working is a bad solution.
> [needs websockets] Add development flake file

- backend/src/injector.py
This fixes issue: The new beta steam client changes the user agent. This causes decky to close browser tabs it shouldn't. This PR fixes that
> Add new user agent

- backend/decky_loader/utilities.py
- frontend/src/plugin-loader.tsx
This PR solves 4 problems:
1. `fetchNoCors` does not prefix explicitly specified headers which can later be overwritten or deleted by `http_request` handler. Arguably, if the user has specified headers explicitly then they must be sent out in the end.
2. `http_handler` would automatically decompress received data, but not intended to do so. Decompressing is now delegate to JS engine.
3. `fetchNoCors` would cache the the request incorrectly under a generic `http://127.0.0.1:1337/fetch` url if the server response asks it to. Caching could be disabled completely for `fetchNoCors`, however another approach was taken - url is added as a query parameter so that the cache is associated correctly with the provided url.
4.  `http_handler` no longer has special headers …
> fix: fetchNoCors and http_request data handling

- backend/decky_loader/localplatform/localplatform.py
- backend/decky_loader/localplatform/localplatformlinux.py
- backend/decky_loader/localplatform/localplatformwin.py
- backend/decky_loader/utilities.py
- frontend/src/steamfixes/index.ts
- frontend/src/steamfixes/socket.ts
this automates lsof and gdb to force close the old CEF debugger socket before steam finishes shutting down (from RegisterForShutdownStart)
Fixes #618
> Work around account switching failing to open the CEF debugger socket

- dist/plugin_loader-prerelease.service
- dist/plugin_loader-release.service
- Steam deck oled (preview os, beta steam)
Docs: https://systemd.io/NETWORK_ONLINE/
Probably good practise to wait until the network manager has started before running decky.
> Ensure boot after network.target

- backend/decky_loader/loader.py
- backend/decky_loader/localplatform/localsocket.py
- backend/decky_loader/main.py
- backend/decky_loader/plugin/plugin.py
- backend/decky_loader/plugin/sandboxed_plugin.py
- dist/install_prerelease.sh
- dist/install_release.sh
- dist/plugin_loader-prerelease.service
- dist/plugin_loader-release.service
- ~Yet to be tested on real hardware; only tested in a decoupled local environment~
- Tested on steam deck oled, preview steam branch
This PR (should) fix timeouts from occuring during shutdown of decky. Plugins are now killed 5 seconds after being asked to shutdown, too.
> Fix shutdown timeouts

- backend/decky_loader/localplatform/localplatformlinux.py
- backend/decky_loader/localplatform/localplatformwin.py
- backend/decky_loader/main.py
- backend/decky_loader/plugin/sandboxed_plugin.py
- backend/decky_loader/updater.py
- Untested
Currently, calls to systemd are done in a blocking fashion. This can possibly create a deadlock.
> Fix updater taking a long time

- backend/decky_loader/utilities.py
Please check the lengthy comment in the code.
This fixes issue: https://github.com/SteamDeckHomebrew/loader-api/issues/8
> fix(http_request): remove conflicting CORS headers

- backend/decky_loader/browser.py
This fixes issue: N/A
After debugging why plugin manual ZIP installations sometimes fail to finish and gets stuck I've noticed that plugin name is being extracted from folder name that is in the ZIP and not from the plugin.json file. This name is then used to search for plugin folder later on in the process (```plugin_folder = self.find_plugin_folder(name)```) and since the plugin folder name is pretty much guaranteed to be different than plugin name - assertion (```assert plugin_folder is not None```) is triggered.
This fixes it by reading the plugin name from plugin.json file that is included in the ZIP.
It might also be a good idea to check why the installer gets stuck when the assertion error is triggered but it is out of scope for this PR.
> fix: Plugin install from ZIP getting stuck indefinitely

- backend/decky_loader/browser.py
Fixes the issue where every 'increment install count' request to the server was sent as a 'new download' even if it should've been 'update from existing install'. (the relevant bit is on line 198)
(Haven't actually tested it as i am doing this from my phone, will update when i get to my laptop)
> Fix the server-side tracking of updates

- frontend/src/store.tsx
This fixes issue: This really isn't fixing any issue, but there is double switch case doing the same thing. The fetch call inside the first switch case is unreachable dead code.
Credits to @KP2048 in https://discord.com/channels/960281551428522045/960284311444131840/1317031315551420447 for noticing it.
> chore: remove dead / double code

- backend/decky_loader/plugin/sandboxed_plugin.py
- Completely untested
This fixes issue: An issue has been reported in the steam deck homebrew discord that uninstalling plugins give a keyerror on uninstall. This fixes that
> Fix id keyerror on plugin uninstall

- backend/decky_loader/browser.py
- backend/decky_loader/locales/en-US.json
- frontend/src/components/DeckyState.tsx
- frontend/src/components/PluginView.tsx
- frontend/src/components/modals/MultiplePluginsInstallModal.tsx
- frontend/src/components/modals/PluginInstallModal.tsx
- frontend/src/components/store/PluginCard.tsx
- frontend/src/components/store/Store.tsx
- frontend/src/plugin-loader.tsx
- frontend/src/plugin.ts
- frontend/src/utils/TranslationHelper.tsx
This fixes issue: #360
Adds some quality-of-life changes to the plugin store browser:
- Add ✓ icon to currently installed plugin version in version selector
- Change install button label depending on the install type that the button would trigger
- Adds icon to install button for clarity
The goal is to make it clear to the user what the current state of the installed plugin is, and what would be the impact of installing the selected version.
> feat: sync with local plugin status in store

- flake.nix
This is a very basic change to the `flake.nix` file, fixing a failure to activate the Nix shell due to missing `setuptools` on my system. A completely fresh Nix environment would not have any python packages installed, so I added it, in order to build `propcache`.
```log
error: builder for '/nix/store/3kvfya2v3vnvbiglh2a5qyh2rai39w3f-python3.11-propcache-0.2.0.drv' failed with exit code 2;
last 25 log lines:
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>   File "/nix/store/hj15fswklkqnsdyqhgap248j7c88kxx9-python3.11-pip-24.0/lib/python3.11/site-packages/pip/_vendor/pyproject_hooks/_impl.py", line 186, in prepare_metadata_for_build_wheel
>     return self._call_hook('prepare_metadata_for_build_wheel', {
> …
```
> chore(flake): Add setuptools in order to build on a minimal Nix system

- frontend/src/components/settings/pages/developer/index.tsx
This PR allows the user to write the plugin URL more easily. If the URL does not contain https:// or http://, the https protocol will be added by default.
| User input                     | Result                         |
| ------------------------------ | ------------------------------ |
| example.com/plugin.zip         | https://example.com/plugin.zip |
| https://example.com/plugin.zip | https://example.com/plugin.zip |
| http://example.com/plugin.zip  | http://example.com/plugin.zip  |
> Simplify the typing of the plugin URL for users

- frontend/package.json
- frontend/pnpm-lock.yaml
- frontend/src/components/modals/filepicker/patches/library.ts
- frontend/src/plugin-loader.tsx
- frontend/src/router-hook.tsx
Update decky/ui to 4.10.1 which includes fixes for `<Menu />` in the new Steam beta.
Parent PR:
https://github.com/SteamDeckHomebrew/decky-frontend-lib/pull/119
> fix(deps): update @decky/ui to version 4.10.2

- frontend/src/components/Markdown.tsx
- frontend/src/components/settings/pages/general/Updater.tsx
This fixes issue: #685
Was removed `FocusRing` component and used just `Focusable` instead, and I modified a little bit UI to be more Steam UI like
> Removed `FocusRing` from Decky Changelog Modal and use `Focusable` instead which fixes: #685
